version: '3.3'

services:
  app:
    build: ./app/
    depends_on:
      mysql:
        condition: service_healthy  

  mysql:
      image: mysql:5.6
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
      volumes:
        - mysql-data:/var/lib/mysql/
        - ./mysql:/docker-entrypoint-initdb.d
        
      healthcheck: 
        test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', "-uroot", "-ppassword"]
        timeout: 7s
        retries: 15
        start_period: 30s
  
  nginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/flask/static:/usr/share/nginx/html/static
    depends_on:
      - app
  
volumes:
  mysql-data:
    driver: local

