
version: '3.3'

services:
  app:
    build: ./app/
    environment:
      - YH_MYSQL_PASSWORD=${YH_MYSQL_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy  

  mysql:
      build: ./mysql/
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${YH_MYSQL_PASSWORD}
      volumes:
        - mysql-data:/var/lib/mysql/
        
      healthcheck: 
        test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', "-uroot", "-p${YH_MYSQL_PASSWORD}"]
        timeout: 7s
        retries: 15
        start_period: 30s
  
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - app
  
volumes:
  mysql-data:
    driver: local
