
version: '3.3'

services:
  app:
    build: ./app/ # when run localy
    # image: pythonflask:latest # when run in jenkins
    depends_on:
      mysql:
        condition: service_healthy  

  mysql:
      build: ./mysql/
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
      volumes:
        - mysql-data:/var/lib/mysql/
        
      healthcheck: 
        test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', "-uroot", "-ppassword"]
        timeout: 7s
        retries: 15
        start_period: 30s
  
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
    depends_on:
      - app
  
volumes:
  mysql-data:
    driver: local
